# Copyright 2021 Marcelo Marcal
# See LICENSE file for licensing details.
#
options:
    extraconfig:
        type: string
        default: ""
        description: |
            Any additional nagios configuration you would like to
            add can be set into this element. It will be placed in
            /etc/nagios4/conf.d/extra.cfg
